name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pklVersion: [ "0.28.2" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install Pkl CLI
        uses: pkl-community/setup-pkl@v0
        with:
          pkl-version: ${{ matrix.pklVersion }}

      - name: Verify Pkl installation
        run: pkl --version

      - name: Cache Dart dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-dart-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-dart-pub-cache-

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze --fatal-infos .

      - name: Run tests
        run: dart test